"use client";

import { useState } from "react";

export default function TimetablePage() {
  const [generated, setGenerated] = useState(false);
  const [schedule, setSchedule] = useState([]);

  const subjects = ["Maths", "Science", "English", "History", "Biology", "Chemistry", "Geography"];
  const sports = ["⚽ Football", "🏀 Basketball", "🏏 Cricket"];
  const extras = ["🎶 Music", "💃 Dance", "🗣 Debate Club", "🎭 Drama"];
  const labs = ["💻 Computer Lab", "🔬 Physics Lab", "🧪 Chemistry Lab"];
  const breaks = ["☕ Break", "🍴 Lunch Break"];

  const days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"];
  const slots = ["9:00 - 10:00", "10:00 - 11:00", "11:00 - 12:00", "12:00 - 1:00", "2:00 - 3:00", "3:00 - 4:00"];

  function getRandomItem(arr) {
    return arr[Math.floor(Math.random() * arr.length)];
  }

  const generateTimetable = () => {
    const tempSchedule = days.map((day) => {
      return {
        day,
        sessions: slots.map((slot) => {
          const roll = Math.random();
          if (roll < 0.5) return getRandomItem(subjects);
          if (roll < 0.65) return getRandomItem(sports);
          if (roll < 0.8) return getRandomItem(extras);
          if (roll < 0.9) return getRandomItem(labs);
          return getRandomItem(breaks);
        }),
      };
    });
    setSchedule(tempSchedule);
    setGenerated(true);
  };

  // PDF Export (prints the timetable area)
  const downloadPDF = () => {
    window.print();
  };

  // WhatsApp Share
  const shareOnWhatsApp = () => {
    const message = encodeURIComponent(
      "📅 Here’s the new timetable generated by Smart Timetable:\n\n" +
        schedule
          .map(
            (row) =>
              `${row.day}: ${row.sessions
                .map((s, i) => `${slots[i]} - ${s}`)
                .join(" | ")}`
          )
          .join("\n") +
        "\n\nShared via Smart Timetable"
    );
    const url = `https://wa.me/?text=${message}`;
    window.open(url, "_blank");
  };

  return (
    <div>
      <h2>➕ Create a New Timetable</h2>
      <p className="mt-4">
        Fill in details below and generate a <b>random demo timetable</b>.  
        You can then download it as PDF or share to WhatsApp groups.
      </p>

      {!generated ? (
        <form
          onSubmit={(e) => {
            e.preventDefault();
            generateTimetable();
          }}
          className="mt-6"
        >
          <label>Program:</label>
          <input type="text" placeholder="e.g. B.Ed Year 1" />

          <label>Semester:</label>
          <select>
            <option>Semester 1</option>
            <option>Semester 2</option>
            <option>Semester 3</option>
            <option>Semester 4</option>
          </select>

          <label>Subjects (comma separated):</label>
          <textarea placeholder="Mathematics, Science, English"></textarea>

          <label>Sports Activities:</label>
          <input type="text" placeholder="Football, Basketball" />

          <label>Extracurriculars:</label>
          <input type="text" placeholder="Music, Dance, Debate Club" />

          <label>Lab Sessions:</label>
          <input type="text" placeholder="Computer Lab, Physics Lab" />

          <label>Break Times:</label>
          <input type="text" placeholder="11:00 AM - 11:30 AM" />

          <label>Custom Notes:</label>
          <textarea placeholder="Any special instructions (e.g. Labs only on Fri)" />

          <button type="submit" className="mt-4">
            ⚡ Generate Dummy Timetable
          </button>
        </form>
      ) : (
        <div className="mt-6">
          <h3>📅 Generated Dummy Timetable</h3>
          <p className="mt-2">This is randomized each time you generate it.</p>

          <div id="timetable-area">
            <table>
              <thead>
                <tr>
                  <th>Day</th>
                  {slots.map((slot) => (
                    <th key={slot}>{slot}</th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {schedule.map((row) => (
                  <tr key={row.day}>
                    <td>{row.day}</td>
                    {row.sessions.map((session, i) => (
                      <td key={i}>{session}</td>
                    ))}
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          <div className="mt-4 flex gap">
            <button onClick={generateTimetable}>🔄 Generate Again</button>
            <button onClick={() => setGenerated(false)}>↩️ Back to Form</button>
            <button onClick={downloadPDF}>📄 Download as PDF</button>
            <button onClick={shareOnWhatsApp}>📲 Send to WhatsApp</button>
          </div>
        </div>
      )}
    </div>
  );
}
